version: '3.4'


services:
  weather_service:
    container_name: 'weather_service'
    restart: always
    build:
      dockerfile: docker/weather_service.Dockerfile
      context: ../
    command: ws_run
    volumes:
      - ../../weather_service:/opt/weather_service
    depends_on:
      - postgres
    env_file:
      - weather_service.env

  nginx:
    container_name: 'weather_nginx'
    restart: on-failure
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather_service

  postgres:
    container_name: 'weather_postgres'
    restart: on-failure
    build:
      dockerfile: docker/postgres.Dockerfile
      context: ../
    volumes:
      - ../.log/.pg_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
